language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kalyano/docker-react -f Docker-dev .

script:
  - docker run -e CI=true kalyano/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker
  env: Docker-env
  access_key_id: AKIA4CDV7FGORFKSVU4Q
  secret_access_key: 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
  bucket_name: "elasticbeanstalk-us-east-1-829176097181"
  bucket_path: "docker"
  on:
    branch: master